config/routes.rb
Rails.application.routes.draw do
  resources :variants
    # resources :sessions

    namespace :admin do

      root "dashboards#index"

      devise_scope :user do
        get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
        get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
      end

      devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :skip => [:registrations]
        as :user do
          get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
          put 'users' => 'devise/registrations#update', :as => 'user_registration'
          patch 'users' => 'devise/registrations#update'
      end

      resources :users
      resources :categories
      resources :products do
        resources :stock_items
        get "stock" => "stock_items#stock", :as => "stock"
      end
      resources :stock_locations

      get "dashboard" => "dashboards#index"
      # get "imports" => "imports#index", :as=>"imports"
      # post "imports/" => "imports#create"
      # get "imports/new" => "imports#new", :as=>"new_import"
      # get "imports/:id/edit" => "imports#edit", :as=>"edit_import"
      # get "imports/:id" => "imports#show", :as=>"import"
      # patch "imports/:id" => "imports#update"
      # put "imports/:id" => "imports#update"
      # delete "imports/:id" => "imports#destroy"
    end

    root "homes#index"
    scope :shopping do
        resources :homes
        resources :products
        get "customer_info/:id" => "customers#customer_info", :as => :customer_info
        get "customer_info/:id/edit_customer_info" => "customers#edit_customer_info", :as => "edit_customer_info"
        patch "customer_info/:id" => "customers#update_customer_info"
        put "customer_info/:id" => "customers#update_customer_info"
        get "product_detail/:id" => "products#product_detail", :as => :product_detail
        resources :customers
        get "cart" => "cart#show"
        get "cart/add/:id" => "cart#add", :as => :add_to_cart
        post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
        post "cart/checkout" => "cart#checkout", :as => :checkout

        post 'session' => 'sessions#create', :as=> :session_customer
        get 'signup' => 'customers#new',:as=> :signup
        get 'logout' => 'sessions#destroy', :as => :logout
        get 'login' => 'sessions#new', :as => :login
      end

  end

app/models/ability.rb
class Ability
  include CanCan::Ability

    def initialize(user)
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :user
      end
    end
end

app/models/category.rb
class Category < ApplicationRecord
  #CallBack
  before_save :update_slug

  #Association
  belongs_to :user
  has_many :products

  #Validation
  validates :category_name, presence: true

  #instance method
  def update_slug
    self.slug = category_name.parameterize
  end

  def to_param
    slug
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  #Association
has_many :orders, :dependent => :destroy
validates :password, presence: true
attr_accessor :password
before_save :prepare_password

#Validation
has_attached_file :image, styles: {
  medium: "300x300>",
  thumb: "100x100>"
}
validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
validates_presence_of :username
validates_uniqueness_of :username, :email, :allow_blank => true
validates_format_of :username, :with => /(?=.*[A-Za-z._@])/, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
validates_presence_of :password, :on => :create
validates_confirmation_of :password
validates_length_of :password, :minimum => 4, :allow_blank => true

#Class Method
def self.authenticate(login, pass)
  customer = find_by_username(login) || find_by_email(login)
  return customer if customer && customer.matching_password?(pass)
end

#Instance Method
def matching_password?(pass)
  self.password_hashL == encrypt_password(pass)
end

private

  def prepare_password
    unless password.blank?
      self.password_salt = Digest::SHA1.hexdigest([Time.now, rand].join)
      self.password_hashL = encrypt_password(password)
    end
  end

  def encrypt_password(pass)
    Digest::SHA1.hexdigest([pass, password_salt].join)
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  before_save :update_slug
  #Call Back
  #Association
  belongs_to :category
  belongs_to :user

  has_many :stock_items
  has_many :stock_location, :through => :stock_items

  #Validation
  validates :product_name, presence: true
  #instance method
  def update_slug
    self.slug = product_name.parameterize
  end

  def to_param
    slug
  end

  def count_on_hand?
    count = stock_items.sum(:quantity)
    if count == 0
      "Out Stock"
    else
      return count
    end
  end



end

app/models/stock_item.rb
class StockItem < ApplicationRecord
  belongs_to :user

  belongs_to :stock_location
  belongs_to :product

  #instance method

  #Validation
  validates :quantity, numericality: { only_integer: true, :greater_than_or_equal_to => 1 }

end

app/models/stock_location.rb
class StockLocation < ApplicationRecord
  belongs_to :user
  has_many :stock_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #Callback

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  after_initialize :set_role_vip, :if => :new_record?
  # Association
  has_many :categories
  has_many :products
  has_many :stock_items
  has_many :stock_locations
  #Devise
  devise :database_authenticatable,:registerable,
  :recoverable, :rememberable, :trackable, :validatable

  #Validation
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  #instance method
  def set_default_role
    self.role ||= :user
  end

  def set_role_vip
    self.role ||= :vip
  end

  def full_name
    "#{first_name}" "#{last_name}"
  end
end

app/models/variant.rb
class Variant < ApplicationRecord
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper


end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/shared/_leftsidebar.html.erb
<div class="navbar-default sidebar" role="navigation" style="overflow: visible;">
    <div class="slimScrollDiv" style="position: relative; overflow: visible; width: auto; height: 100%;"><div class="sidebar-nav navbar-collapse slimscrollsidebar" style="overflow-x: visible; overflow-y: hidden; width: auto; height: 100%;">
        <div class="user-profile">
            <div class="dropdown user-pro-body">
              <%if admin_user_signed_in?%>
                <%if current_admin_user.image.blank?%>
                  <div>
                    <img src="/profile.png" alt="user-img" class="img-circle">
                  </div>
                <%else%>
                  <div>
                    <img src="<%=current_admin_user.image%>" alt="user-img" class="img-circle">
                  </div>
                <%end%>

                <%if current_admin_user.email.blank?%>
                  <a href="#" class="dropdown-toggle u-dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <%="Unknown"%>
                    <span class="caret"></span>
                  </a>
                <%else%>
                  <a href="#" class="dropdown-toggle u-dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <%=current_admin_user.username.to_s.capitalize%>
                    <span class="caret"></span>
                  </a>
                <%end%>
                <ul class="dropdown-menu animated flipInY">
                  <li>
                    <%=link_to  admin_users_path do%>
                      <i class="ti-user"></i> My Profile
                    <%end%>
                  </li>
                  <li>
                    <%=link_to admin_user_path(current_admin_user) do%>
                      <i class="ti-settings"></i> Account Setting
                    <%end%>
                  </li>

                  <li role="separator" class="divider"></li>

                  <li>
                    <%=link_to destroy_admin_user_session_path,method: :delete do%>
                      <i class="fa fa-power-off"></i> Logout
                    <%end%>
                  </li>
                </ul>
              <%else%>

              <%end%>
            </div>
        </div>
        <%= render "shared/link"%>
      </div>
      <div class="slimScrollBar" style="background: rgb(220, 220, 220) none repeat scroll 0% 0%; width: 0px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px; height: 2222px;"></div>
      <div class="slimScrollRail" style="width: 0px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51) none repeat scroll 0% 0%; opacity: 0.2; z-index: 90; right: 1px;"></div>
  </div>
</div>

app/views/shared/_link.html.erb
<ul class="nav in" id="side-menu">
    <li class="sidebar-search hidden-sm hidden-md hidden-lg">
        <!-- input-group -->
        <div class="input-group custom-search-form">
            <input class="form-control" placeholder="Search..." type="text"> <span class="input-group-btn">
        <button class="btn btn-default" type="button"> <i class="fa fa-search"></i> </button>
        </span>
        </div>
        <!-- /input-group -->
    </li>

    <li>
      <%=link_to admin_dashboard_path,:class=>"waves-effect" do%>
        <i class="linea-icon linea-basic fa-fw" data-icon="v"></i>
        <span class="hide-menu">Dashboard</span>
      <%end%>
    </li>
    <%if current_admin_user.try(:admin?) || current_admin_user.try(:vip?)%>
      <li>
        <a href="#" class="waves-effect"><i data-icon="/" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">User<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
          <%if current_admin_user.try(:admin?)  || current_admin_user.try(:vip?)%>
          <li>
            <%=link_to "Add User", new_admin_user_path%>
            <%=link_to "User List", admin_users_path%>
          </li>
          <%else%>
          <li>
            <%=link_to "Import List", users_path%>
          </li>
          <%end%>

        </ul>
      </li>
    <%end%>

    <li>
      <a href="#" class="waves-effect"><i data-icon="/" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Product<span class="fa arrow"></span></a>
      <ul class="nav nav-second-level">
        <%if current_admin_user.try(:admin?)  || current_admin_user.try(:vip?)%>
          <li>
            <%=link_to "Add Product", new_admin_product_path%>
            <%=link_to "Product List", admin_products_path%>
          </li>
        <%else%>
          <li>
            <%=link_to "Product List", admin_products_path%>
          </li>
        <%end%>
      </ul>
    </li>

    <li>
     <a href="#" class="waves-effect"><i data-icon="/" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Category<span class="fa arrow"></span></a>
     <ul class="nav nav-second-level">
       <%if current_admin_user.try(:admin?)  || current_admin_user.try(:vip?)%>
         <li>
           <%=link_to "Add Category", new_admin_category_path%>
           <%=link_to "Category List", admin_categories_path%>
         </li>
       <%else%>
         <li>
           <%=link_to "Category List", admin_categories_path%>
         </li>
       <%end%>

     </ul>
   </li>

   <li>
    <a href="#" class="waves-effect"><i data-icon="/" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Configuration<span class="fa arrow"></span></a>
    <ul class="nav nav-second-level">
      <%if current_admin_user.try(:admin?)  || current_admin_user.try(:vip?)%>
        <li>
          <%=link_to "Stock Location", admin_stock_locations_path%>
        </li>
      <%else%>
      
      <%end%>

    </ul>
  </li>

</ul>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">
        <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse"><i class="ti-menu"></i></a>
        <div class="top-left-part">
            <a class="logo" href="#">
              <b>
                <img src="index_data/pixeladmin-logo.png" alt="home" class="dark-logo"><img src="" alt="home" class="light-logo">
              </b>
                <span class="hidden-xs" style="display: none;">
              <img src="" alt="home" class="dark-logo"><img src="" alt="home" class="light-logo">
             </span>
            </a>
        </div>

        <ul class="nav navbar-top-links navbar-left hidden-xs">
            <li><a href="javascript:void(0)" class="open-close hidden-xs waves-effect waves-light"><i class="ti-menu"></i></a></li>
        </ul>

        <ul class="nav navbar-top-links navbar-right pull-right">
            <!-- Search -->
            <!-- User Setting -->

            <li class="dropdown">
                <a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#">
                    <i class="icon-user"></i>
                    <div class="notify"><span class="heartbit"></span><span class="point"></span></div>
                </a>
                <ul class="dropdown-menu mailbox animated bounceInDown">
                    <li>

                      <div class="drop-title">
                        <%=link_to "Logout",destroy_admin_user_session_path,method: :delete%>
                      </div>

                    </li>

                </ul>
                <!-- /.dropdown-messages -->
            </li>
            <!-- /.dropdown -->
        </ul>
    </div>

</nav>

app/views/shared/css/_10-customs-css2.html.erb
<style media="screen">
/*MAIN COLOR: #f29f29; */

/*.list-socials li a:hover,
.search-form .search-block .search-button,
.box-minicart .cart-block .cart-icon .count,
.box-minicart .cart-inner .group-button-checkout a:hover,
.vertical-wapper .block-title,
.mobile-navigation .icon span,
.main-slideshow .slide-content .button,
.owl-carousel.nav-style1 .owl-nav .owl-prev:hover,
.owl-carousel.nav-style1 .owl-nav .owl-next:hover,
.section-head .section-title,
.product-item .product-inner .quickview-button:hover,
.product-item .group-button a:hover,
.post-item .post-date .month,
.newsletter-form .newsletter-block .submit,
.header.header-home3 .header-nav-wapper,.header.header-home3 .header-nav-wapper .header-nav,
.header.layout4 .search-form .search-block .search-button:hover,
.header.layout5,
.header.layout5 .box-sticky.is-sticky,
.header.layout6 .main-header .top-header,
.header.layout6 .vertical-content,
.header.layout6 .header-nav-wapper,
.header.layout6 .box-sticky.is-sticky .box-minicart .cart-block .cart-icon .count,
.sidebar input[type="checkbox"]:checked + label::after,
.widget_filter_price .ui-slider .ui-slider-handle,
.widget_filter_price .ui-slider .ui-slider-handle,
.widget_filter_price .ui-slider .ui-slider-range,
.list-size li a:hover,
.list-page li a.current,
.list-page li a:hover,
.details-thumb .owl-carousel.has-thumbs .owl-nav .owl-prev:hover,
.details-thumb .owl-carousel.has-thumbs .owl-nav .owl-nex:hover,
.details-info .group-button a:hover,
.kt-tab.nav-tab-style2 .nav > li.active > a,
.content-form .group-button .submit,
.group-changed .changed-item a.active::before,
.post-item.layout3 .post-info .button,
.mfp-close-btn-in .mfp-close,
.kt-popup-newsletter .input-block .input-inner .submit,
.back-to-top:hover::before  {
	background-color: rgba(16, 16, 16, 0.85);
	 }*/
.box-minicart .cart-inner,
.section-head,
.product-item .group-button a:hover,
.item-show .owl-carousel .owl-thumb-item.active,
.sidebar input[type="checkbox"]:checked + label::after,
.list-size li a:hover,
.list-page li a:hover,
.list-page li a.current,
.details-thumb .owl-thumbs .owl-thumb-item.active,
.group-changed .changed-item a.active::before,
.back-to-top {
	border-color: #f29f29;
}

.text-main-color,
.box-minicart .cart-inner .title .count-item,
.box-minicart .cart-inner .subtotal .total-price,
.view-all-categori .button,
.main-menu .demos-menu .demo-item .demo-title .number,
.main-menu .submenu li a:hover,
.main-menu > li:hover > a,
.main-menu > li:hover > a::after,
.topbar .menu-topbar li a:hover,
.kt-panels-actions-wrap .kt-current-panel-title,
.mobile-navigation,
.slideshow1 .item3 .slide-content .subtitle,
.widget-custom-menu ul li a:hover,
.kt-tab .nav > li.active > a,
.kt-tab .nav > li > a:hover,
.product-item .product-name:hover,
.owl-carousel.has-thumbs .owl-nav .owl-prev:hover::before,
.owl-carousel.has-thumbs .owl-nav .owl-next:hover::before,
.post-item .post-info .post-title:hover,
.post-item .post-info .meta-post li a:hover,
.post-item .post-info .button:hover,
.slideshow2 .item3 .slide-content .subtitle,
.featrue-box .block-icon a,
.featrue-box .block-inner .title:hover,
.category-item .category-name:hover,
.category-item .list-cate li a:hover,
.header.layout4 .topbar .menu-topbar li a:hover,
.header.layout4 .main-menu > li > a:hover,
.header.layout4 .menu-item-has-children > a:hover::after,
.product-item.layout4 .product-inner .product-name:hover,
.main-content-home5 .list-recent-posts .product-item .product-name:hover,
.header.layout5 .search-form .search-block .search-button:hover,
.header.layout5 .buytheme:hover,
.slideshow6 .slide-content .smalltitle span,
.header.layout6 .search-form .search-block .search-button:hover,
.loadmore-products .button:hover,
.breadcrumbs a:hover,
.sidebar .label-text:hover,
.widget_filter_price .filter:hover,
.list-style .product-item .group-button .compare-button:hover,
.list-style .product-item .group-button .wishlist-button:hover,
.list-style .product-item .group-button .compare-button:hover .text,
.list-style .product-item .group-button .wishlist-button:hover .text,
.list-style .product-item .availability a:hover,
.top-control .control-button a.active .icon ,
.details-info .availability a:hover,
.quantity .group-quantity-button a:hover,
.login-form .check-box .forgot:hover,
.information-form .list-info li .info a.des:hover,
.shopping-cart-content .delete-item a:hover,
.group-changed .changed-item a:hover::before,
.sidebar .widget .blog-categories > li > a:hover,
.sidebar .widget .blog-categories > li > a:hover::before,
.sidebar .widget-search .search-button:hover,
.post-item .post-info .meta-post .time-post .day,
.main-content-blog .tags .title a:hover,
.kt-popup-newsletter .title,
.kt-popup-newsletter .text-label:hover,
.kt-popup-quickview .details-thumb .owl-carousel.has-thumbs .owl-nav .owl-prev:hover::before,
.kt-popup-quickview .details-thumb .owl-carousel.has-thumbs .owl-nav .owl-next:hover::before {
	color: #f29f29;
}

</style>

app/views/shared/css/_style-partial.html.erb
<%name = [
  "shared/css/1-bootstrap-min",
  "shared/css/2-owl.carousel.min",
  "shared/css/3-font-awesome",
  "shared/css/4-animate.min",
  "shared/css/5-magnific-popup.min",
  "shared/css/6-jquery-ui.min",
  "shared/css/7-jquery.scrollbar",
  "shared/css/8-chosen.min",
  "shared/css/9-style",
  "shared/css/10-customs-css2"
  ]
%>

<%name.each do |n|%>
    <%=render "#{n}"%>
<%end%>

app/views/shared/front-end/sign-up-content/_sign-up.html.erb
<div class="main-content shop-page login-page">
  <div class="container">
    <div class="breadcrumbs">
      <a href="#">Home</a> \ <span class="current"> Login of greate an account</span>
    </div>
    <div class="login-register-form content-form row">
      <!-- Sign IN -->
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="register-form">

          <h4 class="main-title">Great an Account</h4>
          <h5 class="note-title">Registration</h5>
          <%=form_for @customer do |f|%>
          <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
              <%= f.label :username ,:class=>"label-text"%>
              <%= f.text_field :username,:class=>"input-info" %>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
              <%= f.label :email,:class=>"label-text" %>
              <%= f.text_field :email,:class=>"input-info" %>
            </div>
          </div>

          <%= f.label :password ,:class=>"label-text"%>
          <%= f.password_field :password,:class=>"input-info"%>

          <%= f.label :password_confirmation,:class=>"label-text"%>
          <%= f.password_field :password_confirmation,:class=>"input-info" %>

          <div class="group-button"><%=f.submit "Register", :class=>"btn submit"%></div>
          <%end%>
        </div>
      </div>
    </div>
  </div>

  <div class="brand">
    <div class="container">
      <div class="owl-carousel" data-autoplay="false" data-nav="false" data-dots="false" data-loop="false" data-slidespeed="800" data-margin="30"  data-responsive = '{"0":{"items":2}, "640":{"items":3}, "768":{"items":3}, "1024":{"items":4}, "1200":{"items":5}}'>
        <div class="brand-item"><a href="#"><img src="images/brand1.jpg" alt=""></a></div>
        <div class="brand-item"><a href="#"><img src="images/brand1.jpg" alt=""></a></div>
        <div class="brand-item"><a href="#"><img src="images/brand1.jpg" alt=""></a></div>
        <div class="brand-item"><a href="#"><img src="images/brand1.jpg" alt=""></a></div>
        <div class="brand-item"><a href="#"><img src="images/brand1.jpg" alt=""></a></div>
      </div>
    </div>
  </div>
</div>