config/routes.rb
Rails.application.routes.draw do
  resources :variants
    # resources :sessions

    namespace :admin do

      root "dashboards#index"

      devise_scope :user do
        get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
        get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
      end

      devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :skip => [:registrations]
        as :user do
          get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
          put 'users' => 'devise/registrations#update', :as => 'user_registration'
          patch 'users' => 'devise/registrations#update'
      end

      resources :users
      resources :categories
      resources :products do
        resources :stock_items
        get "stock" => "stock_items#stock", :as => "stock"
      end
      resources :stock_locations

      get "dashboard" => "dashboards#index"
      # get "imports" => "imports#index", :as=>"imports"
      # post "imports/" => "imports#create"
      # get "imports/new" => "imports#new", :as=>"new_import"
      # get "imports/:id/edit" => "imports#edit", :as=>"edit_import"
      # get "imports/:id" => "imports#show", :as=>"import"
      # patch "imports/:id" => "imports#update"
      # put "imports/:id" => "imports#update"
      # delete "imports/:id" => "imports#destroy"
    end

    root "homes#index"
    scope :shopping do
        resources :homes
        resources :products
        get "customer_info/:id" => "customers#customer_info", :as => :customer_info
        get "customer_info/:id/edit_customer_info" => "customers#edit_customer_info", :as => "edit_customer_info"
        patch "customer_info/:id" => "customers#update_customer_info"
        put "customer_info/:id" => "customers#update_customer_info"
        get "product_detail/:id" => "products#product_detail", :as => :product_detail
        resources :customers
        get "cart" => "cart#show"
        get "cart/add/:id" => "cart#add", :as => :add_to_cart
        post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
        post "cart/checkout" => "cart#checkout", :as => :checkout

        post 'session' => 'sessions#create', :as=> :session_customer
        get 'signup' => 'customers#new',:as=> :signup
        get 'logout' => 'sessions#destroy', :as => :logout
        get 'login' => 'sessions#new', :as => :login
      end

  end

app/models/stock_item.rb
class StockItem < ApplicationRecord
  belongs_to :user

  belongs_to :stock_location
  belongs_to :product

  #instance method

  #Validation
  validates :quantity, numericality: { only_integer: true, :greater_than_or_equal_to => 1 }

end

app/controllers/admin/stock_items_controller.rb
class Admin::StockItemsController < ApplicationController
  before_action :set_stock_item, only: [:index,:stock,:new,:create,:edit,:update,:destroy]
  before_action :authenticate_admin_user! , only: [:index,:new,:edit,:update,:destroy]
  before_action :admin_only, only: [:new,:edit,:update,:create,:destroy]
  # GET /stock_items
  # GET /stock_items.json

  def stock
    @stock_item = @product.stock_items.new
  end
  
  def index
    @stock_items = @product.stock_items.joins(:product).group(:product_name)
    @fields = ["Product","Quantity", "Stock Location"]

  end

  # GET /stock_items/1
  # GET /stock_items/1.json
  def show

  end

  # GET /stock_items/new
  def new
  end

  # GET /stock_items/1/edit
  def edit
  end

  # POST /stock_items
  # POST /stock_items.json
  def create
    @stock_item = @product.stock_items.new(stock_item_params)

    respond_to do |format|
      if @stock_item.save
        format.html {
          redirect_to admin_product_stock_path,
          notice: 'Stock item was successfully created.'
        }
        format.json { render :show, status: :created, location: @stock_item }
      else
        format.html { render :stock }
        format.json { render json: @stock_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stock_items/1
  # PATCH/PUT /stock_items/1.json
  def update
    respond_to do |format|
      if @stock_item.update(stock_item_params)
        format.html { redirect_to admin_product_stock_items, notice: 'Stock item was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock_item }
      else
        format.html { render :edit }
        format.json { render json: @stock_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_items/1
  # DELETE /stock_items/1.json
  def destroy
    @stock_item.destroy
    respond_to do |format|
      format.html { redirect_to admin_stock_items_url, notice: 'Stock item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_item
      @product = Product.find_by_slug(params[:product_id])
    end

    def admin_only
      unless current_admin_user.admin?
        redirect_to admin_dashboard_path, :alert => "Access denied."
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_item_params
      params.require(:stock_item).permit(:product_id, :stock_location_id, :count_on_hand,:quantity)
    end
end

app/helpers/stock_items_helper.rb
module StockItemsHelper

end

app/views/admin/stock_items/edit.html.erb
<div id="wrapper">
    <!-- Navigation -->
    <%=render "shared/navigation"%>
    <!-- Left navbar-header -->
    <%=render "shared/leftsidebar"%>
    <!-- Left navbar-header end -->
    <!-- Page Content -->
    <div id="page-wrapper" style="min-height: 613px;">
      <div class="container-fluid">
        <div class="row bg-title">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Add Product</h4>
            </div>
        </div>
        <!-- Content -->
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-info">
                    <div class="panel-wrapper collapse in" aria-expanded="true">
                        <div class="panel-body">
                          <%=form_for([:admin, @product, @stock_item]) do |f|%>
                                <div class="form-body">
                                    <h3 class="box-title">Form Product</h3>
                                    <hr>
                                    <div class="row">
                                      <div class="col-md-6">
                                        <div class="form-group">
                                          <%=f.label "Quantity", :class=>"control-label"%>
                                          <%=f.number_field :quantity, :class=>"form-control", :placeholder=>"Quantity"%>
                                        </div>
                                      </div>
                                        <!--/span-->

                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "Product Name", :class=>"control-label"%>
                                            <%=f.collection_select :product_id,Product.all,:id,:product_name, {}, {:class => 'form-control'}%>
                                          </div>
                                        </div>

                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "Stock Location", :class=>"control-label"%>
                                            <%=f.collection_select :stock_location_id,StockLocation.all,:id,:name, {}, {:class => 'form-control'}%>
                                          </div>
                                        </div>

                                        <!--/span-->
                                    </div>
                                    <!--/row-->
                                </div>
                                <div class="form-actions">
                                  <%=f.submit "Add", :class=>"btn btn-success" do%>
                                    <i class="fa fa-check"></i>
                                  <%end%>
                                  <%=link_to "Cancel", admin_products_path, :class=>"btn btn-default", :style=>"color:black"%>
                                </div>
                            <%end%>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>

        <!-- /.container-fluid -->
        <footer class="footer text-center">Panhara &copy; Copyright </footer>
    </div>
    <!-- /#page-wrapper -->
  </div>
</div>

app/views/admin/stock_items/index.html.erb
<div id="wrapper">
    <!-- Navigation -->
    <%=render "shared/navigation"%>
    <!-- Left navbar-header -->
    <%=render "shared/leftsidebar"%>
    <!-- Left navbar-header end -->
    <!-- Page Content -->
    <div id="page-wrapper" style="min-height: 613px;">
      <div class="container-fluid">
        <div class="row bg-title">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Stock</h4>
            </div>
        </div>
        <!-- Content -->
        <div class="row">
          <div class="col-md-4 col-lg-6 col-xs-12">
            <div class="white-box">
              <h3 class="box-title">Product Detail</h3>
              <ul class="basic-list">
                <%@stock_items.each do |stock|%>
                  <li>Product Name <span class="pull-right"><%=stock.product.product_name%></span></li>
                  <li>Quantity <span class="pull-right"><%=stock.product.count_on_hand?%></span></li>
                  <li>Stock Location <span class="pull-right"><%=link_to stock.stock_location.name, admin_stock_location_path(stock.stock_location.id)%></span></li>
                <%end%>
              </ul>
            </div>
          </div>
        </div>
      </div>

        <!-- /.container-fluid -->
        <footer class="footer text-center">Panhara &copy; Copyright </footer>
    </div>
    <!-- /#page-wrapper -->
  </div>
</div>

app/views/admin/stock_items/stock.html.erb
<div id="wrapper">
    <!-- Navigation -->
    <%=render "shared/navigation"%>
    <!-- Left navbar-header -->
    <%=render "shared/leftsidebar"%>
    <!-- Left navbar-header end -->
    <!-- Page Content -->
    <div id="page-wrapper" style="min-height: 613px;">
      <div class="container-fluid">
        <div class="row bg-title">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title"><%=@product.product_name%></h4>
            </div>
        </div>

        <%=render "/layouts/flash"%>

        <!-- Content -->
      <%=form_for([:admin, @product, @stock_item]) do |f|%>
        <%=f.error_messages%>
        <div class="row">
            <div class="col-md-8">
                <div class="panel panel-info">
                    <div class="panel-wrapper collapse in" aria-expanded="true">
                        <div class="panel-body">
                                <div class="form-body">
                                    <h3 class="box-title">Form Product</h3>
                                    <hr>
                                    <div class="row">
                                        <!--/span-->
                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "Quantity", :class=>"control-label"%>
                                            <%=f.number_field :quantity, :class=>"form-control", :placeholder=>"Quantity"%>
                                          </div>
                                        </div>

                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "Stock Location", :class=>"control-label"%>
                                            <%=f.collection_select :stock_location_id,StockLocation.all,:id,:name, {}, {:class => 'form-control'}%>
                                          </div>
                                        </div>
                                        <!--/span-->
                                        <div class="col-lg-12 col-md-12 col-sm-4 col-xs-12">
                                          <ul class="list-group list-group-full">
                                            <li class="list-group-item">
                                              <span class="badge badge-success"><%=@product.count_on_hand?%></span> Count On Hand
                                            </li>
                                          </ul>
                                        </div>
                                    </div>
                                    <!--/row-->
                                </div>


                                <div class="form-actions">
                                  <%=f.submit "Add", :class=>"btn btn-success" do%>
                                    <i class="fa fa-check"></i>
                                  <%end%>
                                  <%=link_to "Cancel", admin_products_path, :class=>"btn btn-default", :style=>"color:black"%>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
            <%end%>
            <div class="col-md-4">
                <div class="panel panel-info">
                    <div class="panel-wrapper collapse in" aria-expanded="true">
                        <div class="panel-body">
                          <div class="p-20">
                            <h3 class="box-title">Add Another Field</h3>
                              <div class="list-group">
                                <%=link_to "Default",edit_admin_product_path(@product),:class=>"list-group-item", :style=>"border-radius:0px !important;color:black;"%>
                                <%=link_to "Image","#",:class=>"list-group-item", :style=>"border-radius:0px !important;color:black;"%>
                                <%=link_to "Stock",admin_product_stock_path(@product),:class=>"list-group-item", :style=>"border-radius:0px !important;color:black;"%>

                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>

        <!-- /.container-fluid -->
        <footer class="footer text-center">Panhara &copy; Copyright </footer>
    </div>
    <!-- /#page-wrapper -->
  </div>
</div>