config/routes.rb
Rails.application.routes.draw do
  resources :variants
    # resources :sessions

    namespace :admin do

      root "dashboards#index"

      devise_scope :user do
        get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
        get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
      end

      devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :skip => [:registrations]
        as :user do
          get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
          put 'users' => 'devise/registrations#update', :as => 'user_registration'
          patch 'users' => 'devise/registrations#update'
      end

      resources :users
      resources :categories
      resources :products do
        resources :stock_items
        get "stock" => "stock_items#stock", :as => "stock"
      end
      resources :stock_locations

      get "dashboard" => "dashboards#index"
      # get "imports" => "imports#index", :as=>"imports"
      # post "imports/" => "imports#create"
      # get "imports/new" => "imports#new", :as=>"new_import"
      # get "imports/:id/edit" => "imports#edit", :as=>"edit_import"
      # get "imports/:id" => "imports#show", :as=>"import"
      # patch "imports/:id" => "imports#update"
      # put "imports/:id" => "imports#update"
      # delete "imports/:id" => "imports#destroy"
    end

    root "homes#index"
    scope :shopping do
        resources :homes
        resources :products
        get "customer_info/:id" => "customers#customer_info", :as => :customer_info
        get "customer_info/:id/edit_customer_info" => "customers#edit_customer_info", :as => "edit_customer_info"
        patch "customer_info/:id" => "customers#update_customer_info"
        put "customer_info/:id" => "customers#update_customer_info"
        get "product_detail/:id" => "products#product_detail", :as => :product_detail
        resources :customers
        get "cart" => "cart#show"
        get "cart/add/:id" => "cart#add", :as => :add_to_cart
        post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
        post "cart/checkout" => "cart#checkout", :as => :checkout

        post 'session' => 'sessions#create', :as=> :session_customer
        get 'signup' => 'customers#new',:as=> :signup
        get 'logout' => 'sessions#destroy', :as => :logout
        get 'login' => 'sessions#new', :as => :login
      end

  end

app/models/variant.rb
class Variant < ApplicationRecord
end

app/controllers/admin/variants_controller.rb
class VariantsController < ApplicationController
  before_action :set_variant, only: [:show, :edit, :update, :destroy]

  # GET /variants
  # GET /variants.json
  def index
    @variants = Variant.all
  end

  # GET /variants/1
  # GET /variants/1.json
  def show
  end

  # GET /variants/new
  def new
    @variant = Variant.new
  end

  # GET /variants/1/edit
  def edit
  end

  # POST /variants
  # POST /variants.json
  def create
    @variant = Variant.new(variant_params)

    respond_to do |format|
      if @variant.save
        format.html { redirect_to @variant, notice: 'Variant was successfully created.' }
        format.json { render :show, status: :created, location: @variant }
      else
        format.html { render :new }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variants/1
  # PATCH/PUT /variants/1.json
  def update
    respond_to do |format|
      if @variant.update(variant_params)
        format.html { redirect_to @variant, notice: 'Variant was successfully updated.' }
        format.json { render :show, status: :ok, location: @variant }
      else
        format.html { render :edit }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variants/1
  # DELETE /variants/1.json
  def destroy
    @variant.destroy
    respond_to do |format|
      format.html { redirect_to variants_url, notice: 'Variant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variant
      @variant = Variant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variant_params
      params.fetch(:variant, {})
    end
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/admin/variants/_form.html.erb
<%= simple_form_for(@variant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/variants/edit.html.erb
<h1>Editing Variant</h1>

<%= render 'form', variant: @variant %>

<%= link_to 'Show', @variant %> |
<%= link_to 'Back', variants_path %>

app/views/admin/variants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Variants</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variants.each do |variant| %>
      <tr>
        <td><%= link_to 'Show', variant %></td>
        <td><%= link_to 'Edit', edit_variant_path(variant) %></td>
        <td><%= link_to 'Destroy', variant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variant', new_variant_path %>

app/views/admin/variants/new.html.erb
<h1>New Variant</h1>

<%= render 'form', variant: @variant %>

<%= link_to 'Back', variants_path %>

app/views/admin/variants/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_variant_path(@variant) %> |
<%= link_to 'Back', variants_path %>