config/routes.rb
Rails.application.routes.draw do
  resources :variants
    # resources :sessions

    namespace :admin do

      root "dashboards#index"

      devise_scope :user do
        get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
        get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
      end

      devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :skip => [:registrations]
        as :user do
          get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
          put 'users' => 'devise/registrations#update', :as => 'user_registration'
          patch 'users' => 'devise/registrations#update'
      end

      resources :users
      resources :categories
      resources :products do
        resources :stock_items
        get "stock" => "stock_items#stock", :as => "stock"
      end
      resources :stock_locations

      get "dashboard" => "dashboards#index"
      # get "imports" => "imports#index", :as=>"imports"
      # post "imports/" => "imports#create"
      # get "imports/new" => "imports#new", :as=>"new_import"
      # get "imports/:id/edit" => "imports#edit", :as=>"edit_import"
      # get "imports/:id" => "imports#show", :as=>"import"
      # patch "imports/:id" => "imports#update"
      # put "imports/:id" => "imports#update"
      # delete "imports/:id" => "imports#destroy"
    end

    root "homes#index"
    scope :shopping do
        resources :homes
        resources :products
        get "customer_info/:id" => "customers#customer_info", :as => :customer_info
        get "customer_info/:id/edit_customer_info" => "customers#edit_customer_info", :as => "edit_customer_info"
        patch "customer_info/:id" => "customers#update_customer_info"
        put "customer_info/:id" => "customers#update_customer_info"
        get "product_detail/:id" => "products#product_detail", :as => :product_detail
        resources :customers
        get "cart" => "cart#show"
        get "cart/add/:id" => "cart#add", :as => :add_to_cart
        post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
        post "cart/checkout" => "cart#checkout", :as => :checkout

        post 'session' => 'sessions#create', :as=> :session_customer
        get 'signup' => 'customers#new',:as=> :signup
        get 'logout' => 'sessions#destroy', :as => :logout
        get 'login' => 'sessions#new', :as => :login
      end

  end

app/models/product.rb
class Product < ApplicationRecord
  before_save :update_slug
  #Call Back
  #Association
  belongs_to :category
  belongs_to :user

  has_many :stock_items
  has_many :stock_location, :through => :stock_items

  #Validation
  validates :product_name, presence: true
  #instance method
  def update_slug
    self.slug = product_name.parameterize
  end

  def to_param
    slug
  end

  def count_on_hand?
    count = stock_items.sum(:quantity)
    if count == 0
      "Out Stock"
    else
      return count
    end
  end



end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin_user!, only: [:index,:new,:edit,:update,:destroy]
  before_action :admin_only, only: [:index,:new,:edit,:update,:create,:destroy]
  # GET /categories
  # GET /categories.json
  def index
    @products = Product.all
    @fields = ["ID","Product","Price","Category","User"]
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @product = current_admin_user.products.build
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @product = current_admin_user.products.build(create_product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to edit_admin_product_path(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @product.update(update_product_params)
        format.html { redirect_to edit_admin_product_path(@product), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find_by_slug(params[:id])
    end

    def admin_only
      unless current_admin_user.admin?
        redirect_to admin_dashboard_path, :alert => "Access denied."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_product_params
      params.require(:product).permit(:product_name,:sku,:master_price,:category_id)
    end
    def update_product_params
      params.require(:product).permit(:product_name,:sku,:master_price,:category_id,
                                      :cost_price,:available_on,:discount_on,:description,
                                      :slug,:meta_description,:meta_keyword,:color,:category_id,
                                      :promotionable)
    end
end

app/controllers/products_controller.rb
class ProductsController < NewApplicationController
  def index

  end
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/views/admin/products/edit.html.erb
<div id="wrapper">
    <!-- Navigation -->
    <%=render "shared/navigation"%>
    <!-- Left navbar-header -->
    <%=render "shared/leftsidebar"%>
    <!-- Left navbar-header end -->
    <!-- Page Content -->
    <div id="page-wrapper" style="min-height: 613px;">
      <div class="container-fluid">
        <div class="row bg-title">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Edit Product</h4>
            </div>
        </div>
        <!-- Content -->
        <div class="row">
            <div class="col-md-8">
                <div class="panel panel-info">
                    <div class="panel-wrapper collapse in" aria-expanded="true">
                        <div class="panel-body">

                          <%=form_for([:admin, @product]) do |f|%>
                                <div class="form-body">
                                    <h3 class="box-title">Form Product</h3>
                                    <hr>
                                    <div class="row">
                                      <div class="col-md-6">
                                        <div class="form-group">
                                          <%=f.label "Product", :class=>"control-label"%>
                                          <%=f.text_field :product_name, :class=>"form-control", :placeholder=>"Product Name"%>
                                        </div>
                                      </div>
                                        <!--/span-->
                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "SKU", :class=>"control-label"%>
                                            <%=f.text_field :sku, :class=>"form-control", :placeholder=>"SKU"%>
                                          </div>
                                        </div>
                                        <!--/span-->
                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "Master Price", :class=>"control-label"%>
                                            <%=f.text_field :master_price, :class=>"form-control", :placeholder=>"Master Price"%>
                                          </div>
                                        </div>


                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "Product Name", :class=>"control-label"%>
                                            <%=f.collection_select :category_id,Category.all,:id,:category_name, {}, {:class => 'form-control'}%>
                                          </div>
                                        </div>

                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "Availble On", :class=>"control-label"%>
                                            <%=f.text_field :available_on, :class=>"form-control", :placeholder=>"mm/dd/yyyy",:id=>"datetimepicker1"%>
                                          </div>
                                        </div>

                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "Discount On", :class=>"control-label"%>
                                            <%=f.text_field :discount_on, :class=>"form-control", :placeholder=>"mm/dd/yyyy",:id=>"datetimepicker2"%>
                                          </div>
                                        </div>

                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "Color", :class=>"control-label"%>
                                            <%=f.text_field :color, :class=>"form-control", :placeholder=>"Color"%>
                                          </div>
                                        </div>

                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "Slug", :class=>"control-label"%>
                                            <%=f.text_field :slug, :class=>"form-control", :placeholder=>"Slug"%>
                                          </div>
                                        </div>

                                        <div class="col-md-12">
                                          <div class="form-group">
                                            <%=f.label "Description", :class=>"control-label"%>
                                            <%=f.text_area :description, :class => 'form-control'%>
                                          </div>
                                        </div>

                                        <div class="col-md-12">
                                          <div class="form-group">
                                            <%=f.label "Meta Description", :class=>"control-label"%>
                                            <%=f.text_area :meta_description, :class => 'form-control'%>
                                          </div>
                                        </div>

                                        <div class="col-md-12">
                                          <div class="form-group">
                                            <%=f.label "Meta Keyword", :class=>"control-label"%>
                                            <%=f.text_area :meta_keyword, :class => 'form-control'%>
                                          </div>
                                        </div>
                                        <!--/span-->
                                    </div>
                                    <!--/row-->
                                </div>
                                <div class="form-actions">
                                  <%=f.submit "Save", :class=>"btn btn-success" do%>
                                    <i class="fa fa-check"></i>
                                  <%end%>
                                  <%=link_to "Cancel", admin_products_path, :class=>"btn btn-default", :style=>"color:black"%>
                                </div>
                            <%end%>


                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-info">
                    <div class="panel-wrapper collapse in" aria-expanded="true">
                        <div class="panel-body">
                          <div class="p-20">
                            <h3 class="box-title">Add Another Field</h3>
                              <div class="list-group">
                                <%=link_to "Default",edit_admin_product_path(@product),:class=>"list-group-item", :style=>"border-radius:0px !important;color:black;"%>
                                <%=link_to "Image","#",:class=>"list-group-item", :style=>"border-radius:0px !important;color:black;"%>
                                <%=link_to "Stock",admin_product_stock_path(@product),:class=>"list-group-item", :style=>"border-radius:0px !important;color:black;"%>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>

        <!-- /.container-fluid -->
        <footer class="footer text-center">Panhara &copy; Copyright </footer>
    </div>
    <!-- /#page-wrapper -->
  </div>
</div>

app/views/admin/products/index.html.erb
<div id="wrapper">
    <!-- Navigation -->
    <%=render "shared/navigation"%>
    <!-- Left navbar-header -->
    <%=render "shared/leftsidebar"%>
    <!-- Left navbar-header end -->
    <!-- Page Content -->
    <div id="page-wrapper" style="min-height: 613px;">
      <div class="container-fluid">
        <div class="row bg-title">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Products</h4>
            </div>
        </div>
        <!-- Content -->
        <div class="col-sm-12">
          <div class="white-box">
            <%if admin_user_signed_in?%>
              <%if current_admin_user.try(:admin?)%>
                <%=link_to new_admin_product_path, :class=>"btn btn-success waves-effect waves-light" do%>
                    <span class="btn-label"><i class="fa fa-user"></i></span>Add Product
                <%end%>
              <%end%>
            <%end%>
              <h3 class="box-title"></h3>
              <div class="table-responsive">
                  <table class="table">
                      <thead>
                          <tr>
                              <%@fields.each do |f|%>
                                <th><%=f%></th>
                              <%end%>
                          </tr>
                      </thead>
                      <tbody>
                        <%@products.each do |product|%>
                          <tr>
                            <td>
                              <%=product.id%>
                            </td>
                            <td>
                              <%=product.product_name%>
                            </td>
                            <td>
                              <%=number_to_currency(product.master_price)%>
                            </td>
                            <td>
                              <%=product.category.category_name%>
                            </td>

                            <td>
                              <%=product.user.username%>
                            </td>

                            <td class="text-nowrap">
                              <%if current_admin_user.try(:admin?) || current_admin_user.try(:vip?)%>
                              <%=link_to admin_product_stock_items_path(product) do%>
                              <i class="fa fa-dropbox text-inverse m-r-10"></i>
                              <%end%>
                                <%=link_to admin_product_path(product) do%>
                                  <i class="fa fa-eye text-inverse m-r-10"></i>
                                <%end%>
                                <%=link_to edit_admin_product_path(product) do%>
                                  <i class="fa fa-pencil text-inverse m-r-10"></i>
                                <%end%>
                                <%=link_to  admin_product_path(product), method: :delete, data: { confirm: "Are You Sure ?"} do%>
                                  <i class="fa fa-close text-danger"></i>
                                <%end%>
                              <%else%>
                                <%=link_to admin_product_path(product) do%>
                                  <i class="fa fa-eye text-inverse m-r-10"></i>
                                <%end%>
                              <%end%>
                            </td>
                          </tr>
                          <%end%>
                      </tbody>
                  </table>
              </div>
          </div>
      </div>
      </div>

        <!-- /.container-fluid -->
        <footer class="footer text-center">Panhara &copy; Copyright </footer>
    </div>
    <!-- /#page-wrapper -->
  </div>
</div>

app/views/admin/products/new.html.erb
<div id="wrapper">
    <!-- Navigation -->
    <%=render "shared/navigation"%>
    <!-- Left navbar-header -->
    <%=render "shared/leftsidebar"%>
    <!-- Left navbar-header end -->
    <!-- Page Content -->
    <div id="page-wrapper" style="min-height: 613px;">
      <div class="container-fluid">
        <div class="row bg-title">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Add Product</h4>
            </div>
        </div>
        <!-- Content -->
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-info">
                    <div class="panel-wrapper collapse in" aria-expanded="true">
                        <div class="panel-body">
                          <%=form_for([:admin, @product]) do |f|%>
                                <div class="form-body">
                                    <h3 class="box-title">Form Product</h3>
                                    <hr>
                                    <div class="row">
                                      <div class="col-md-6">
                                        <div class="form-group">
                                          <%=f.label "Product", :class=>"control-label"%>
                                          <%=f.text_field :product_name, :class=>"form-control", :placeholder=>"Product Name"%>
                                        </div>
                                      </div>
                                        <!--/span-->
                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "SKU", :class=>"control-label"%>
                                            <%=f.text_field :sku, :class=>"form-control", :placeholder=>"SKU"%>
                                          </div>
                                        </div>
                                        <!--/span-->
                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "Master Price", :class=>"control-label"%>
                                            <%=f.text_field :master_price, :class=>"form-control", :placeholder=>"Master Price"%>
                                          </div>
                                        </div>

                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <%=f.label "Product Name", :class=>"control-label"%>
                                            <%=f.collection_select :category_id,Category.all,:id,:category_name, {}, {:class => 'form-control'}%>
                                          </div>
                                        </div>

                                        <!--/span-->
                                    </div>
                                    <!--/row-->
                                </div>
                                <div class="form-actions">
                                  <%=f.submit "Save", :class=>"btn btn-success" do%>
                                    <i class="fa fa-check"></i>
                                  <%end%>
                                  <%=link_to "Cancel", admin_products_path, :class=>"btn btn-default", :style=>"color:black"%>
                                </div>
                            <%end%>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>

        <!-- /.container-fluid -->
        <footer class="footer text-center">Panhara &copy; Copyright </footer>
    </div>
    <!-- /#page-wrapper -->
  </div>
</div>

app/views/admin/products/show.html.erb
<div id="wrapper">
    <!-- Navigation -->
    <%=render "shared/navigation"%>
    <!-- Left navbar-header -->
    <%=render "shared/leftsidebar"%>
    <!-- Left navbar-header end -->
    <!-- Page Content -->
    <div id="page-wrapper" style="min-height: 613px;">
      <div class="container-fluid">
        <div class="row bg-title">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title"><%=@product.product_name%></h4>
            </div>
        </div>
          <div class="row">

            <div class="col-md-4 col-lg-6 col-xs-12">
              <div class="white-box">
                <h3 class="box-title">Product Detail</h3>
                <ul class="basic-list">
                  <li>Product Name <span class="pull-right"><%=@product.product_name%></span></li>
                  <li>SKU <span class="pull-right"><%=@product.sku%></span></li>
                  <li>Category <span class="pull-right"><%=@product.category.category_name%></span></li>
                  <li>Master Price<span class="pull-right"><%=@product.master_price%></span></li>
                  <li>Cost Price <span class="pull-right"><%=@product.cost_price%></span></li>
                </ul>
              </div>
            </div>

            <div class="col-md-4 col-lg-6 col-xs-12">
              <div class="white-box">
                <h3 class="box-title" style="color:white;">text</h3>
                <ul class="basic-list">
                  <li>Available On <span class="pull-right"><%=@product.available_on%></span></li>
                  <li>Discount On<span class="pull-right"><%=@product.discount_on%></span></li>
                  <li>Color <span class="pull-right"><%=@product.color%></span></li>
                  <li>Promotionable <span class="pull-right"><%=@product.promotionable%></span> </li>
                </ul>
              </div>
            </div>

            <div class="col-md-4 col-lg-6 col-xs-12">
              <div class="white-box">
                <h3 class="box-title" style="color:white;">text</h3>
                <ul class="basic-list">
                  <li>Meta Description <span class="pull-right"></span></li>
                  <li>Meta Keyword<span class="pull-right"></span></li>
                  <li>Slug <span class="pull-right"></li>
                  <li>Promotionable <span class="pull-right"></span> </li>
                </ul>
              </div>
            </div>

          </div>
          </div>
        <!-- /.container-fluid -->
        <footer class="footer text-center">Panhara &copy; Copyright </footer>
      </div>
    <!-- /#page-wrapper -->
  </div>
</div>